-- Table會員
CREATE TABLE MEMBER(
	MEMBER_ID INT AUTO_INCREMENT NOT NULL COMMENT '會員ID',
	MEMBER_EMAIL VARCHAR(100) NOT NULL COMMENT '會員信箱',
	MEMBER_PASSWORD VARCHAR(10) NOT NULL COMMENT '會員密碼',
	MEMBER_NAME VARCHAR(10)  COMMENT '會員名稱',
	MEMBER_PIC VARCHAR(100) COMMENT '會員頭貼',
	MEMBER_FANS INT DEFAULT 0 COMMENT '會員粉絲數',
	MEMBER_AGE INT  COMMENT '會員年齡',
	MEMBER_GENDER INT  COMMENT'會員性別',
	MEMBER_BIRTH DATE  COMMENT '會員生日',
	MEMBER_PHONE VARCHAR(10) COMMENT '會員電話',
	MEMBER_ADDRESS VARCHAR(20) COMMENT '會員地址',
	MEMBER_POINT INT NOT NULL DEFAULT 0 COMMENT '會員積分',
	MEMBER_CREATE_TIME TIMESTAMP NOT NULL default CURRENT_TIMESTAMP COMMENT '會員註冊時間',
	MEMBER_UPDATE_TIME TIMESTAMP NOT NULL  default CURRENT_TIMESTAMP COMMENT '會員更新時間',
	MEMBER_STATUS INT NOT NULL DEFAULT 1 COMMENT '會員狀態',
	CONSTRAINT MEMBER_MEMBER_ID_PK PRIMARY KEY(MEMBER_ID),
    CONSTRAINT MEMBER_MEMBER_EMAIL_UK UNIQUE (MEMBER_EMAIL)
);



-- Table用戶追蹤明細
CREATE TABLE MEMBER_FOLLOWER(
	MEMBER_FOLLOWER_ID INT NOT NULL AUTO_INCREMENT COMMENT '用戶追蹤明細ID',
	MEMBER_ID INT NOT NULL COMMENT '用戶ID',
	MEMBER_ID_FOLLOWER INT NOT NULL COMMENT '追蹤用戶ID',
	CONSTRAINT MEMBER_FOLLOWER_MEMBER_FOLLOWER_ID_PK PRIMARY KEY(MEMBER_FOLLOWER_ID),
	CONSTRAINT MEMBER_FOLLOWER_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	CONSTRAINT MEMBER_FOLLOWER_MEMBER_ID_FOLLOWER_FK FOREIGN KEY (MEMBER_ID_FOLLOWER) REFERENCES MEMBER (MEMBER_ID)
);

-- Table商店
CREATE TABLE SHOP (
  	SHOP_ID INT AUTO_INCREMENT NOT NULL COMMENT '商家ID',
  	MEMBER_ID INT NOT NULL COMMENT '商家持有人ID',
  	SHOP_TAX_ID char(8) NOT NULL COMMENT '統一編號',
  	SHOP_NAME VARCHAR(50) NOT NULL COMMENT '商家名稱',
  	SHOP_ZIP_CODE VARCHAR(6) NOT NULL COMMENT '商家郵遞區號',
  	SHOP_CITY CHAR(6) NOT NULL COMMENT "商家縣市",
  	SHOP_ADDRESS LONGTEXT NOT NULL COMMENT "商家地址",
  	SHOP_LATITUDE DECIMAL(11,8) NOT NULL COMMENT "商家所在地經度",
  	SHOP_LONGITUDE DECIMAL(11,8) NOT NULL COMMENT "商家所在地緯度",
  	SHOP_DESCRIPTION LONGTEXT COMMENT "商家介紹",
  	SHOP_TAG TEXT COMMENT "商家標籤",
  	SHOP_RATING DECIMAL(2,1) NOT NULL DEFAULT '0.0' COMMENT "商家評價",
  	SHOP_RATING_COUNT INT NOT NULL DEFAULT '0' COMMENT "總評價數",
  	SHOP_RATING_TOTAL INT NOT NULL DEFAULT '0' COMMENT "總評價加總",
  	SHOP_EMAIL VARCHAR(100) DEFAULT NULL COMMENT "商家信箱",
  	SHOP_PHONE VARCHAR(50) NOT NULL COMMENT "商家電話",
  	SHOP_PRICE_LEVEL DECIMAL(10,2) DEFAULT NULL COMMENT "商家均消",
  	SHOP_OPENING_TIME TEXT COMMENT "商家營業時間",
  	SHOP_WEBSITE VARCHAR(200) DEFAULT NULL COMMENT "商家網站",
  	SHOP_MAIN_IMG BLOB COMMENT "商家主圖片",
  	SHOP_GALLERY TEXT COMMENT "商家圖片庫",
  	SHOP_CREATE_TIME TIMESTAMP NOT NULL default CURRENT_TIMESTAMP  COMMENT "商家建立時間",
  	SHOP_UPDATE_TIME TIMESTAMP DEFAULT NULL default CURRENT_TIMESTAMP COMMENT "商家更新時間",
  	SHOP_TOTAL_VIEW INT NOT NULL DEFAULT '0' COMMENT "商家總瀏覽數",
  	SHOP_RESERV_STATUS INT NOT NULL DEFAULT '0' COMMENT "商家是否開放預約",
  	CONSTRAINT SHOP_SHOP_ID_PK PRIMARY KEY (SHOP_ID),
  	CONSTRAINT SHOP_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
	);
-- 專欄文章分類 --
CREATE TABLE ARTICLE_CATEGORY (
	ARTICLE_CATEGORY_ID INT AUTO_INCREMENT NOT NULL COMMENT '文章分類編號',
	ARTICLE_CATEGORY_NAME VARCHAR(50) COMMENT '文章分類名稱',
	CONSTRAINT ARTICLE_CATEGORY_ARTICLE_CATEGORY_ID_PK PRIMARY KEY (ARTICLE_CATEGORY_ID)
);

-- 專欄文章 --
CREATE TABLE ARTICLE (
	ARTICLE_ID INT AUTO_INCREMENT NOT NULL COMMENT '文章編號',
	ARTICLE_TITLE VARCHAR(50) COMMENT '文章標題',
	ARTICLE_CONTENT	LONGTEXT COMMENT '文章內容',
	ARTICLE_CREATE_TIME TIMESTAMP COMMENT '文章上架時間',
	ARTICLE_COLLECTIONS INT COMMENT '文章收藏次數',
	ARTICLE_VERIFY_STATUS INT COMMENT '文章審核狀態',
	ARTICLE_STATUS INT COMMENT '文章狀態',
	MEMBER_ID INT COMMENT '專欄撰寫者編號',
	SHOP_ID INT COMMENT '專欄撰寫對象餐廳編號',
	ARTICLE_CATEGORY_ID INT COMMENT '文章分類編號',	
	CONSTRAINT ARTICLE_ARTICLE_ID_PK PRIMARY KEY (ARTICLE_ID),
	CONSTRAINT ARTICLE_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	CONSTRAINT ARTICLE_SHOP_ID_FK FOREIGN KEY (SHOP_ID) REFERENCES SHOP (SHOP_ID),
	CONSTRAINT ARTICLE_CATEGORY_ID_FK FOREIGN KEY (ARTICLE_CATEGORY_ID) REFERENCES ARTICLE_CATEGORY (ARTICLE_CATEGORY_ID)		
);

-- 專欄文章收藏 --
CREATE TABLE ARTICLE_FAVORITE (
	ARTICLE_FAVORITE_ID INT AUTO_INCREMENT NOT NULL COMMENT '文章收藏明細編號',
	MEMBER_ID INT COMMENT '文章收藏會員編號',
	ARTICLE_ID INT COMMENT '收藏文章編號',	
	CONSTRAINT ARTICLE_FAVORITE_ARTICLE_FAVORITE_ID_PK PRIMARY KEY (ARTICLE_FAVORITE_ID),
	CONSTRAINT ARTICLE_FAVORITE_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	CONSTRAINT ARTICLE_FAVORITE_ARTICLE_ID_FK FOREIGN KEY (ARTICLE_ID) REFERENCES ARTICLE (ARTICLE_ID)
);

-- 產品分類 --
CREATE TABLE PRODUCT_CATEGORY (
	PRODUCT_CATEGORY_ID INT AUTO_INCREMENT NOT NULL COMMENT '產品分類編號',
	PRODUCT_CATEGORY_NAME VARCHAR(50) COMMENT '積分產品分類名稱',
	CONSTRAINT PRODUCT_CATEGORY_PRODUCT_CATEGORY_ID_PK PRIMARY KEY (PRODUCT_CATEGORY_ID)
);

-- 積分商城產品 --
CREATE TABLE PRODUCT (
	PRODUCT_ID INT AUTO_INCREMENT NOT NULL COMMENT '產品編號',
	PRODUCT_NAME VARCHAR(50) COMMENT '產品名稱',
	PRODUCT_INTRO LONGTEXT COMMENT '產品介紹',
	PRODUCT_POINT INT COMMENT '產品所需積分',
	PRODUCT_STOCK_QUANTITY INT COMMENT '產品庫存數量',
	PRODUCT_IMG BLOB COMMENT '產品圖片',
	PRODUCT_STATUS INT COMMENT '產品上架狀態',
	PRODUCT_CATEGORY_ID INT COMMENT '產品分類編號',
	CONSTRAINT PRODUCT_PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID),
	CONSTRAINT PRODUCT_PRODUCT_CATEGORY_ID_FK FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (PRODUCT_CATEGORY_ID)
);





-- 訂單 --
CREATE TABLE ORDERS (
	ORDERS_ID INT AUTO_INCREMENT NOT NULL COMMENT '訂單編號',
	MEMBER_ID INT COMMENT '訂購人編號',
	ORDERS_DATE TIMESTAMP COMMENT '訂購時間',
	ORDERS_TOTAL_POINT INT COMMENT '訂購總需積分',
	ORDERS_SHIPPING_NAME VARCHAR(50) COMMENT '收件人名字',
	ORDERS_SHIPPING_PHONE VARCHAR(50) COMMENT '收件人電話',
	ORDERS_SHIPPING_ZIP INT COMMENT '收貨所在地區碼',
	ORDERS_SHIPPING_ADDRESS VARCHAR(200) COMMENT '收貨地址',
	CONSTRAINT ORDERS_ORDERS_ID_PK PRIMARY KEY (ORDERS_ID),
	CONSTRAINT ORDERS_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);


-- 訂單明細 --
CREATE TABLE ORDER_ITEM (
	ORDER_ITEM_ID INT AUTO_INCREMENT NOT NULL COMMENT '訂單明細編號',
	PRODUCT_ID INT COMMENT '產品編號',
	ORDERS_ID	INT COMMENT '訂單編號',
	ORDER_ITEM_AMOUNT INT COMMENT '商品數量',
	ORDER_ITEM_POINT INT COMMENT '商品所需積分',
	CONSTRAINT ORDER_ITEM_ORDER_ITEM_ID_PK PRIMARY KEY (ORDER_ITEM_ID),
	CONSTRAINT ORDER_ITEM_PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID),
	CONSTRAINT ORDER_ITEM_ORDERS_ID_FK FOREIGN KEY (ORDERS_ID) REFERENCES ORDERS (ORDERS_ID)
);

-- 優惠專區 --
CREATE TABLE DISCOUNT (
	DISCOUNT_ID INT AUTO_INCREMENT NOT NULL COMMENT '優惠專區編號',
	DISCOUNT_TYPE VARCHAR(50) COMMENT '優惠類型',
	DISCOUNT_DESC VARCHAR(50) COMMENT '優惠細節描述',
	DISCOUNT_START_DATE DATETIME COMMENT '優惠開始時間',
	DISCOUNT_EXPIRE_DATE DATETIME COMMENT '優惠結束時間',
	DISCOUNT_AMOUNT INT COMMENT '優惠券發行數量',
	DISCOUNT_STATUS INT COMMENT '優惠發行狀態',
	SHOP_ID INT COMMENT '優惠餐廳編號',
	CONSTRAINT DISCOUNT_DISCOUNT_ID_PK PRIMARY KEY (DISCOUNT_ID),
	CONSTRAINT DISCOUNT_SHOP_ID_FK FOREIGN KEY (SHOP_ID) REFERENCES SHOP (SHOP_ID)	
);


-- Table餐廳評論
CREATE TABLE COMMENT(
	COMMENT_ID INT NOT NULL AUTO_INCREMENT COMMENT '餐廳評論ID',
	MEMBER_ID INT NOT NULL COMMENT '評論會員ID',
	SHOP_ID INT NOT NULL COMMENT '被評論餐廳ID',
	COMMENT_CONTENT LONGTEXT NOT NULL COMMENT'評論內容',
	COMMENT_RATING DECIMAL(2,1) NOT NULL default 0 COMMENT'餐廳評分',
	COMMENT_TIME TIMESTAMP NOT NULL default CURRENT_TIMESTAMP COMMENT'評論時間',
	COMMENT_STATUS INT NOT NULL default 1 COMMENT'評論狀態',
	CONSTRAINT COMMENT_COMMENT_ID_PK PRIMARY KEY(COMMENT_ID),
	CONSTRAINT COMMENT_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	CONSTRAINT COMMENT_SHOP_ID_FK FOREIGN KEY (SHOP_ID) REFERENCES SHOP (SHOP_ID)
);


-- Table 餐廳收藏
CREATE TABLE SHOP_FAVORITES(
	SHOP_FAVORITES_ID INT NOT NULL AUTO_INCREMENT COMMENT '餐廳追蹤明細編號',
	MEMBER_ID INT NOT NULL COMMENT '收藏會員ID',
	SHOP_ID INT NOT NULL COMMENT '被收藏餐廳ID',
	CONSTRAINT SHOP_FAVORITES_SHOP_FAVORITES_ID_PK PRIMARY KEY (SHOP_FAVORITES_ID),
	CONSTRAINT SHOP_FAVORITES_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	CONSTRAINT SHOP_FAVORITES_SHOP_ID_FK FOREIGN KEY (SHOP_ID) REFERENCES SHOP (SHOP_ID)
);







-- TABLE-討論區發文
CREATE TABLE FORUM_POST (
		FORUM_POST_ID INT AUTO_INCREMENT NOT NULL COMMENT '討論區發文編號 PK',
    	MEMBER_ID INT NOT NULL COMMENT '發文會員ID FK',
    	FORUM_POST_TITEL VARCHAR(50) NOT NULL COMMENT '發文標題',
    	FORUM_POST_CONTENT LONGTEXT NOT NULL COMMENT '發文內容',
		FORUM_POST_TIME TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '發文時間', 
    	FORUM_POST_UPDATE_TIME TIMESTAMP COMMENT '發文最新編輯時間',
    	FORUM_POST_REPLY_TOTAL INT DEFAULT 0 COMMENT '發文回復總數',
    	FORUM_POST_LIKE INT DEFAULT 0 COMMENT '發文被點讚次數', -- DEFAULT 0
    	FORUM_POST_STATUS INT NOT NULL DEFAULT 1 COMMENT '發文狀態 0:下架 1:上架',

    	CONSTRAINT FORUM_POST_PK PRIMARY KEY (FORUM_POST_ID), 
    	CONSTRAINT FK_FORUM_POST_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

-- TABLE-討論區發文按讚
CREATE TABLE FORUM_POST_LIKE (
		FORUM_POST_LIKE_ID INT AUTO_INCREMENT NOT NULL COMMENT '討論區發文按讚編號 PK',
    	FORUM_POST_ID INT NOT NULL COMMENT '被按讚的發文編號 FK',
    	MEMBER_ID INT NOT NULL COMMENT '按讚會員ID FK',
    
    	CONSTRAINT FORUM_POST_LIKE_PK PRIMARY KEY (FORUM_POST_LIKE_ID),
    	CONSTRAINT FK_FORUM_POST_LIKE_FORUM_POST_ID FOREIGN KEY (FORUM_POST_ID) REFERENCES FORUM_POST (FORUM_POST_ID),
    	CONSTRAINT FK_FORUM_POST_LIKE_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    
    	CONSTRAINT UK_FORUM_POST_LIKE_FORUM_POST_ID_AND_MEMBER_ID UNIQUE KEY (FORUM_POST_ID, MEMBER_ID)
);

-- TABLE-討論區發文檢舉
CREATE TABLE FORUM_POST_REPORT (
		FORUM_POST_REPORT_ID INT AUTO_INCREMENT NOT NULL COMMENT '討論區發文檢舉編號 PK',
    	FORUM_POST_ID INT NOT NULL COMMENT '被檢舉的發文編號 FK',
    	MEMBER_ID INT NOT NULL COMMENT '檢舉會員ID FK',
    	FORUM_POST_REPORT_REASON VARCHAR(100) NOT NULL COMMENT '檢舉原因',
    	FORUM_POST_REPORT_TIME TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '檢舉時間', 
    	FORUM_POST_REPORT_STATUS INT NOT NULL DEFAULT 0 COMMENT '處理狀態 0:未處理 1:未通過 2:通過',
    
    	CONSTRAINT FORUM_POST_REPORT_PK PRIMARY KEY (FORUM_POST_REPORT_ID),
    	CONSTRAINT FK_FORUM_POST_REPORT_FORUM_POST_ID FOREIGN KEY (FORUM_POST_ID) REFERENCES FORUM_POST (FORUM_POST_ID),
    	CONSTRAINT FK_FORUM_POST_REPORT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    
    	CONSTRAINT UK_FORUM_POST_REPORT_FORUM_POST_ID_AND_MEMBER_ID UNIQUE KEY (FORUM_POST_ID, MEMBER_ID)
);

-- TABLE-討論區回覆
CREATE TABLE FORUM_REPLY (
		FORUM_REPLY_ID INT AUTO_INCREMENT NOT NULL COMMENT '討論區回覆編號 PK',
    	MEMBER_ID INT NOT NULL COMMENT '發表回覆會員ID',
    	FORUM_POST_ID INT NOT NULL COMMENT '回覆發文編號',
    	FORUM_REPLY_CONTENT LONGTEXT NOT NULL COMMENT '回覆內容',
    	FORUM_REPLY_TIME TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '回覆時間',
    	FORUM_REPLY_UPDATE_TIME TIMESTAMP COMMENT '回覆最新編及時間',
    	FORUM_REPLY_STATUS INT DEFAULT 1 COMMENT '回復狀態 0:下架 1:上架',
    	FORUM_REPLY_LIKE INT DEFAULT 0 COMMENT '回覆被點讚次數', -- DEFAULT 0
    
    	CONSTRAINT FORUM_REPLY_PK PRIMARY KEY (FORUM_REPLY_ID),
    	CONSTRAINT FK_FORUM_REPLY_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    	CONSTRAINT FK_FORUM_REPLY_FORUM_POST_ID FOREIGN KEY (FORUM_POST_ID) REFERENCES FORUM_POST (FORUM_POST_ID)
);


-- TABLE-討論區回覆按讚
CREATE TABLE FORUM_REPLY_LIKE (
		FORUM_REPLY_LIKE_ID INT AUTO_INCREMENT NOT NULL COMMENT '回覆按讚編號 PK',
    	FORUM_REPLY_ID INT NOT NULL COMMENT '被按讚的回覆編號 FK',
    	MEMBER_ID INT NOT NULL COMMENT '按讚會員ID FK',
    
    	CONSTRAINT FORUM_REPLY_LIKE_PK PRIMARY KEY (FORUM_REPLY_LIKE_ID),
    	CONSTRAINT FK_FORUM_REPLY_LIKE_FORUM_REPLY_ID FOREIGN KEY (FORUM_REPLY_ID) REFERENCES FORUM_REPLY (FORUM_REPLY_ID),
		CONSTRAINT FK_FORUM_REPLY_LIKE_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    	CONSTRAINT UK_FORUM_REPLY_LIKE_FORUM_REPLY_ID_AND_MEMBER_ID UNIQUE KEY (FORUM_REPLY_ID, MEMBER_ID)
);

-- TABLE-討論區回覆檢舉
CREATE TABLE FORUM_REPLY_REPORT (
		FORUM_REPLY_REPORT_ID INT AUTO_INCREMENT NOT NULL COMMENT '討論區回覆檢舉編號 PK',
    	FORUM_REPLY_ID INT NOT NULL COMMENT '被檢舉回覆的編號 FK',
    	MEMBER_ID INT NOT NULL COMMENT '檢舉會員ID FK',
    	FORUM_REPLY_REPORT_REASON VARCHAR(100) NOT NULL COMMENT '檢舉原因',
    	FORUM_REPLY_REPORT_TIME TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '檢舉時間',
    	FORUM_REPLY_REPORT_STATUS INT NOT NULL DEFAULT 0 COMMENT '處理狀態 0:未處理 1:未通過 2:通過',
    
    	CONSTRAINT FORUM_REPLY_REPORT_PK PRIMARY KEY (FORUM_REPLY_REPORT_ID),
		CONSTRAINT FK_FORUM_REPLY_REPORT_FORUM_REPLY_ID FOREIGN KEY (FORUM_REPLY_ID) REFERENCES FORUM_REPLY (FORUM_REPLY_ID),
    	CONSTRAINT FK_FORUM_REPLY_REPORT_MEMBER_ID FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    	CONSTRAINT UK_FORUM_REPLY_REPORT_FORUM_REPLY_ID_AND_MEMBER_ID UNIQUE KEY (FORUM_REPLY_ID, MEMBER_ID)
);


-- 餐廳訂位
CREATE TABLE RESERV (
		RESERV_ID INT AUTO_INCREMENT NOT NULL COMMENT '餐廳訂位編號',
    	SHOP_ID INT NOT NULL COMMENT '定位餐廳編號',
    	RESERV_PEOPLE_LIMITED INT NOT NULL COMMENT '訂位人數上限',
    	RESERV_PERIOD_STATUS INT DEFAULT 0 NOT NULL COMMENT '定位時段狀態 0:未開放 1:開放中',
    	RESERV_PARTY_STATUS INT DEFAULT 0 NOT NULL COMMENT '揪團開放狀態 0:未開放 1:開放揪團',
    
    	CONSTRAINT RESERV_RESERV_ID_PK PRIMARY KEY (RESERV_ID),
    	CONSTRAINT RESERV_SHOP_ID_FK FOREIGN KEY (SHOP_ID) REFERENCES SHOP (SHOP_ID)
    
);

-- 餐廳訂位明細
CREATE TABLE RESERV_ORDER (
		RESERV_ORDER_ID INT AUTO_INCREMENT NOT NULL COMMENT '餐廳訂位明細編號',
    	MEMBER_ID INT NULL COMMENT '定位人編號',
    	RESERV_ID INT NOT NULL COMMENT '預約餐廳編號',
    	RESERV_ORDER_DATE DATE NOT NULL COMMENT '定位日期',
    	RESERV_ORDER_PERIOD TIMESTAMP NOT NULL COMMENT '預約時段',
    	RESERV_ORDER_STATUS INT NOT NULL COMMENT '預約訂單狀態',
		RESERV_ORDER_PEOPLE_AMOUNT INT NOT NULL COMMENT '預約人數',
    	RESERV_ORDER_PHONE VARCHAR(10) NOT NULL COMMENT '預約人電話',
    
    	CONSTRAINT RESERV_ORDER_RESERV_ORDER_ID_PK PRIMARY KEY (RESERV_ORDER_ID),
    	CONSTRAINT RESERV_ORDER_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    	CONSTRAINT RESERV_ORDER_RESERV_ID_FK FOREIGN KEY (RESERV_ID) REFERENCES RESERV (RESERV_ID)
);


-- 揪團列表
CREATE TABLE PARTY(
		PARTY_ID INT AUTO_INCREMENT NOT NULL COMMENT '揪團編號',
		MEMBER_ID INT NOT NULL COMMENT '揪團發起人會員ID',
    	SHOP_ID INT NOT NULL COMMENT '揪團目的地餐廳ID',
    	RESERV_ID INT NOT NULL COMMENT '揪團餐廳訂位ID',
    	PARTY_TITLE VARCHAR(50) NOT NULL COMMENT '揪團標題',
    	PARTY_START_TIME DATETIME NOT NULL COMMENT '揪團開始時間',
    	PARTY_END_TIME DATETIME NOT NULL COMMENT '揪團結束時間',
    	PARTY_INTRO LONGTEXT COMMENT '揪團介紹',
    	PARTY_PARTICIPANTS_MAX INT NOT NULL COMMENT '成團人數最多限制',
    	PARTY_PARTICIPANTS_MIN INT NOT NULL COMMENT '成團人數最少限制', 
    	PARTY_STATUS INT DEFAULT 0 COMMENT '揪團狀態 0:未成立 1:已成立',
    
    	CONSTRAINT PARTY_PARTY_ID_PK PRIMARY KEY (PARTY_ID),
    	CONSTRAINT PARTY_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    	CONSTRAINT PARTY_SHOP_ID_FK FOREIGN KEY (SHOP_ID) REFERENCES SHOP (SHOP_ID),
    	CONSTRAINT PARTY_RESERV_ID_FK FOREIGN KEY (RESERV_ID) REFERENCES RESERV (RESERV_ID)
);


-- 揪團報名表
CREATE TABLE PARTY_PARTICIPANTS (
		PARTY_PARTICIPANTS_ID INT AUTO_INCREMENT NOT NULL COMMENT '揪團報名者編號',
    	PARTY_MEMBER_ID INT NOT NULL COMMENT '參與會員編號',
    	PARTY_ID INT NOT NULL COMMENT '揪團編號',
    	PARTY_UP_TIME TIMESTAMP NOT NULL COMMENT '報名時間',
    
    	CONSTRAINT PARTY_PARTICIPANTS_PARTY_PARTICIPANTS_ID_PK PRIMARY KEY (PARTY_PARTICIPANTS_ID),
    	CONSTRAINT PARTY_PARTICIPANTS_PARTY_MEMBER_ID_FK FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    	CONSTRAINT PARTY_PARTICIPANTS_PARTY_ID_FK FOREIGN KEY (PARTY_ID) REFERENCES PARTY (PARTY_ID)
);


-- Table 網頁設定
CREATE TABLE WEBSITE_SETTING (
	WEBSITE_URL VARCHAR(100) COMMENT '網站網址' ,
	SITE_TITLE VARCHAR(50) NOT NULL COMMENT '網站標題',
	FOOTER_TEXT VARCHAR(100) COMMENT '頁腳文字',
	SITE_LOGO BLOB COMMENT '網站LOGO',
	SITE_STATUS INT NOT NULL COMMENT '網站狀態',
    
	CONSTRAINT WEBSITE_SETTING_WEBSITE_URL_PK PRIMARY KEY (WEBSITE_URL)
) ;



-- Table 管理員
CREATE TABLE MANAGER (
	MANAGER_ID INT AUTO_INCREMENT NOT NULL COMMENT '管理員ID', 
	MANAGER_ACCOUNT VARCHAR(10) NOT NULL COMMENT '管理員帳號',
	MANAGER_NAME VARCHAR(50) NOT NULL COMMENT '管理員名稱',
	MANAGER_PIC BLOB COMMENT '管理員頭貼',
	MANAGER_EMAIL VARCHAR(20) COMMENT '管理員信箱',
	MANAGER_PASSWORD VARCHAR(10) NOT NULL COMMENT '管理員密碼',
	MANAGER_PHONE VARCHAR(10) COMMENT '管理員電話',

	CONSTRAINT MANAGER_MANAGER_ID_PK PRIMARY KEY (MANAGER_ID)
) ;
